import React from 'react'
import './index.css'
import  {
    AppwriteAuthComponent,
    GoogleAuth,
    FacebookAuth,
    // TwitterAuth,
    GithubAuth,
    EmailAuth,
    MicrosoftAuth,
    AppleAuth,
    PhoneAuth,
    AmazonAuth,
    AuthO,
    DiscordAuth,
    SpotifyAuth,
    TwitchAuth,
    AutodeskAuth,
    AuthentikAuth,
    BitBucketAuth,
    BoxAuth,
    DailyMotionAuth,
    DisqusAuth,
    DropBoxAuth,
    EtsyAuth,
    GitlabAuth,
    LinkedinAuth,
    NotionAuth,
    OktaAuth,
    PaypalAuth,
    PodioAuth,
    SalesforceAuth,
    SlackAuth,
    TradeshiftAuth,
    WordpressAuth,
    YahooAuth,
    YandexAuth,
    ZoomAuth,
    BitlyAuth, 
    StripeAuth,
    YammerAuth
  } from './Components/index.js'
import {AuthButton} from './Helper/index.js'
import {useAuthUser} from './Hooks/index.js'


export {
    AppwriteAuthComponent,
    // GoogleAuth,
    // FacebookAuth,
    // TwitterAuth,
    // GithubAuth,
    // EmailAuth, 
    // MicrosoftAuth,
    // AppleAuth,
    // PhoneAuth,
    // AmazonAuth,
    // AuthO,
    // DiscordAuth,
    // SpotifyAuth,
    // TwitchAuth,
    // AutodeskAuth,
    // AuthentikAuth,
    // BitBucketAuth,
    // BoxAuth,
    // DailyMotionAuth,
    // DisqusAuth,
    // DropBoxAuth,
    // EtsyAuth,
    // GitlabAuth,
    // LinkedinAuth,
    // NotionAuth,
    // OktaAuth,
    // PaypalAuth,
    // PodioAuth,
    // SalesforceAuth,
    // SlackAuth,
    // TradeshiftAuth,
    // WordpressAuth,
    // YahooAuth,
    // YandexAuth,
    // ZoomAuth,
    // BitlyAuth,
    // StripeAuth,
    // YammerAuth,
    AuthButton,
    useAuthUser
}